# Generated by Django 5.2 on 2026-04-13 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0002_produto_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='total',
        ),
    ]
