# Generated by Django 5.2 on 2026-04-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0003_remove_produto_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
